<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>AutoFarmScreenshot</RootNamespace>
    <AssemblyName>AutoFarmScreenshot</AssemblyName>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseSharedCompilation>false</UseSharedCompilation>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>

  <PropertyGroup>
    <GamePath Condition="'$(GamePath)' == '' and Exists('/Applications/Stardew Valley.app/Contents/MacOS')">/Applications/Stardew Valley.app/Contents/MacOS</GamePath>
    <GamePath Condition="'$(GamePath)' == '' and Exists('$(HOME)/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/MacOS')">$(HOME)/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/MacOS</GamePath>
  </PropertyGroup>

  <ItemGroup Condition="'$(GamePath)' != ''">
    <Reference Include="MonoGame.Framework">
      <HintPath>$(GamePath)/MonoGame.Framework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Stardew Valley">
      <HintPath>$(GamePath)/Stardew Valley.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="StardewValley.GameData">
      <HintPath>$(GamePath)/StardewValley.GameData.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="StardewModdingAPI">
      <HintPath>$(GamePath)/StardewModdingAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="xTile">
      <HintPath>$(GamePath)/xTile.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
